# Generated by Django 6.0.6 on 2026-09-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='signature',
            field=models.TextField(blank=True, help_text='Dilithium signature over encrypted_content (base64 encoded)', null=True),
        ),
        migrations.AddField(
            model_name='userkeys',
            name='signing_private_key',
            field=models.TextField(blank=True, help_text='Dilithium (ML-DSA-44) private key (base64 encoded)', null=True),
        ),
        migrations.AddField(
            model_name='userkeys',
            name='signing_public_key',
            field=models.TextField(blank=True, help_text='Dilithium (ML-DSA-44) public key (base64 encoded)', null=True),
        ),
    ]
