# Generated by Django 6.0.6 on 2026-09-17 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_signature_userkeys_signing_private_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkeys',
            name='rotated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
